package com.lizl.news.constant

object AppConstant
{
    const val BUNDLE_NEWS_TITLE = "BUNDLE_NEWS_TITLE"
    const val BUNDLE_NEWS_URL = "BUNDLE_NEWS_URL"
    const val BUNDLE_NEWS_SOURCE = "BUNDLE_NEWS_SOURCE"
    const val BUNDLE_URL = "BUNDLE_URL"

    const val NEWS_SOURCE_ZHIHU_DAILY = "NEWS_SOURCE_ZHIHU_DAILY"
    const val NEWS_SOURCE_ZHIHU_TOP = "NEWS_SOURCE_ZHIHU_TOP"

    const val NEWS_SOURCE_DAILY_36_KR = "NEWS_SOURCE_DAILY_36_KR"
    const val NEWS_SOURCE_DAILY_IT_HOME = "NEWS_SOURCE_DAILY_IT_HOME"
    const val NEWS_SOURCE_DAILY_SS_PAI = "NEWS_SOURCE_DAILY_SS_PAI"
    const val NEWS_SOURCE_DAILY_HU_XIU = "NEWS_SOURCE_DAILY_HU_XIU"
    const val NEWS_SOURCE_DAILY_JIAN_DAN = "NEWS_SOURCE_DAILY_JIAN_DAN"
    const val NEWS_SOURCE_DAILY_HU_PU = "NEWS_SOURCE_DAILY_HU_PU"
    const val NEWS_SOURCE_DAILY_THE_PAPER = "NEWS_SOURCE_DAILY_THE_PAPER"
    const val NEWS_SOURCE_DAILY_WEIBO = "NEWS_SOURCE_DAILY_WEIBO"
    const val NEWS_SOURCE_DAILY_V2EX = "NEWS_SOURCE_DAILY_V2EX"
    const val NEWS_SOURCE_DAILY_GAME_CORE = "NEWS_SOURCE_DAILY_GAME_CORE"
    const val NEWS_SOURCE_DAILY_YYS = "NEWS_SOURCE_DAILY_YYS"
}