package com.lizl.news.constant

object AppConstant
{
    const val BUNDLE_DATA_OBJECT = "BUNDLE_DATA_OBJECT"
    const val BUNDLE_DATA_STRING_ARRAY = "BUNDLE_DATA_STRING_ARRAY"
    const val BUNDLE_DATA_STRING = "BUNDLE_DATA_STRING"
    const val BUNDLE_DATA_BOOLEAN = "BUNDLE_DATA_BOOLEAN"
    const val BUNDLE_DATA_INT = "BUNDLE_DATA_INT"

    const val NEWS_PLATFORM_ZHIHU = "NEWS_PLATFORM_ZHIHU"
    const val NEWS_PLATFORM_DAILY_HOT = "NEWS_PLATFORM_DAILY_HOT"

    const val NEWS_SOURCE_ZHIHU_DAILY = "NEWS_SOURCE_ZHIHU_DAILY"
    const val NEWS_SOURCE_ZHIHU_TOP = "NEWS_SOURCE_ZHIHU_TOP"

    const val NEWS_SOURCE_DAILY_36_KR = "NEWS_SOURCE_DAILY_36_KR"
    const val NEWS_SOURCE_DAILY_IT_HOME = "NEWS_SOURCE_DAILY_IT_HOME"
    const val NEWS_SOURCE_DAILY_SS_PAI = "NEWS_SOURCE_DAILY_SS_PAI"
    const val NEWS_SOURCE_DAILY_HU_XIU = "NEWS_SOURCE_DAILY_HU_XIU"
    const val NEWS_SOURCE_DAILY_JIAN_DAN = "NEWS_SOURCE_DAILY_JIAN_DAN"
    const val NEWS_SOURCE_DAILY_HU_PU = "NEWS_SOURCE_DAILY_HU_PU"
    const val NEWS_SOURCE_DAILY_THE_PAPER = "NEWS_SOURCE_DAILY_THE_PAPER"
    const val NEWS_SOURCE_DAILY_WEIBO = "NEWS_SOURCE_DAILY_WEIBO"
}