package com.lizl.news.constant

object AppConstant {
    const val BUNDLE_DATA_OBJECT = "BUNDLE_DATA_OBJECT"
    const val BUNDLE_DATA_STRING_ARRAY = "BUNDLE_DATA_STRING_ARRAY"
    const val BUNDLE_DATA_STRING = "BUNDLE_DATA_STRING"
    const val BUNDLE_DATA_BOOLEAN = "BUNDLE_DATA_BOOLEAN"
    const val BUNDLE_DATA_INT = "BUNDLE_DATA_INT"

    const val NEWS_PLATFORM_ZHIHU = "NEWS_PLATFORM_ZHIHU"
    const val NEWS_PLATFORM_HEADLINE = "NEWS_PLATFORM_HEADLINE"
    const val NEWS_PLATFORM_DAILY_HOT = "NEWS_PLATFORM_DAILY_HOT"

    const val NEWS_SOURCE_ZHIHU_DAILY = "NEWS_SOURCE_ZHIHU_DAILY"
    const val NEWS_SOURCE_ZHIHU_TOP = "NEWS_SOURCE_ZHIHU_TOP"
    const val NEWS_SOURCE_DAILY_BRIEFING = "NEWS_SOURCE_DAILY_BRIEFING"
    const val NEWS_SOURCE_HEADLINE_GAME = "NEWS_SOURCE_HEADLINE_GAME"
    const val NEWS_SOURCE_HEADLINE_ANIMATION = "NEWS_SOURCE_HEADLINE_ANIMATION"
    const val NEWS_SOURCE_HEADLINE_NBA = "NEWS_SOURCE_HEADLINE_NBA"
    const val NEWS_SOURCE_HEADLINE_IT = "NEWS_SOURCE_HEADLINE_IT"
    const val NEWS_SOURCE_HEADLINE_INTERNET = "NEWS_SOURCE_HEADLINE_INTERNET"
    const val NEWS_SOURCE_HEADLINE_SCIENCE = "NEWS_SOURCE_HEADLINE_SCIENCE"
    const val NEWS_SOURCE_HEADLINE_DOMESTIC = "NEWS_SOURCE_HEADLINE_DOMESTIC"
    const val NEWS_SOURCE_HEADLINE_INTERNATIONAL = "NEWS_SOURCE_HEADLINE_INTERNATIONAL"
    const val NEWS_SOURCE_HEADLINE_SOCIAL = "NEWS_SOURCE_HEADLINE_SOCIAL"
}